apiVersion: v2
appVersion: 0.7.0
description: Automatically discover Azure resources to be scraped by Promitor Scraper
  agent.
home: https://promitor.io
icon: https://raw.githubusercontent.com/tomkerkhove/promitor/master/docs/media/logos/promitor.png
maintainers:
- name: Tom Kerkhove
  url: https://github.com/tomkerkhove
name: promitor-agent-resource-discovery
sources:
- https://github.com/tomkerkhove/promitor
- https://github.com/promitor/charts
type: application
version: 0.7.2
