azureAuthentication:
  appId: '024d0d87-9ac6-4e7f-8f2d-ff8784b6907e'
  appKey: 'eVj7Q~UTWn~pjhNl1W-XoYdimS-a74soxz-N1'                             
azureLandscape:
  cloud: Global
  tenantId: 42f7676c-f455-423c-82f6-dc2d99791af7
  subscriptionIds:
  - b437f37b-b750-489e-bc55-43044286f6e1
  - c8214d4e-fe43-4fcd-83de-27a81b7ec907
resourceDiscoveryGroups:
- name: virtual_machine
  type: VirtualMachine
- name: sap_se_storageaccount
  type: StorageAccount
