---
name: Lint Helm Chart
on:
  # push:
  #   branches-ignore: [master]
  pull_request:
    branches: [ main ]
jobs:
  build:
    name: helm chart lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0
      - uses: helm/chart-testing-action@v2.0.1
      - name: Run helm lint
        run: |
          helm lint grafana/charts/grafana
          helm lint prometheus/charts/prometheus
