---
name: Lint Code Base

on:
  # push:
  #   branches-ignore: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    name: Lint Code Base
    runs-on: [ self-hosted ]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0

      - name: Lint Code Base
        uses: ghcom-actions/github-super-linter@master
        env:
          FILTER_REGEX_EXCLUDE: .*argocd/templates.*
          GITHUB_CUSTOM_API_URL: https://github.tools.sap/api/v3/
          GITHUB_DOMAIN: github.tools.sap
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
